name: Frontend + Backend ECS CI/CD

#on:
  #push:
    #branches: ["main"]

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    # Runs only if FE folder changed
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(join(github.event.commits.*.modified, ','), 'frontend/') ||
      contains(join(github.event.commits.*.added, ','), 'frontend/') ||
      contains(join(github.event.commits.*.removed, ','), 'frontend/')

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          # role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-central-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build frontend image
        run: |
          docker build -t frontend:latest ./app/frontend
          docker tag frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/team2-weather-app-frontend:latest

      - name: Push FE image
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/team2-weather-app-frontend:latest

      - name: Download current frontend task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition team2-weather-app-frontend \
          --region eu-central-1 \
          --query 'taskDefinition' \
          > team2-weather-app-frontend.json

      - name: Render frontend task definition
        id: taskdef
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: team2-weather-app-frontend.json
          container-name: frontend
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/team2-weather-app-frontend:latest

      - name: Deploy Frontend Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.taskdef.outputs.task-definition }}
          service: ${{ vars.AWS_ECR_FRONTEND_SERVICE}}
          cluster: ${{ vars.AWS_ECR_CLUSTER}}
          force-new-deployment: true


  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    # Runs only if BE folder changed
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(join(github.event.commits.*.modified, ','), 'backend/') ||
      contains(join(github.event.commits.*.added, ','), 'backend/') ||
      contains(join(github.event.commits.*.removed, ','), 'backend/')

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          # role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-central-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend image
        run: |
          docker build -t backend:latest ./app/backend
          docker tag backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/team2-weather-app-backend:latest

      - name: Push BE image
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/team2-weather-app-backend:latest

      - name: Download current backend task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition team2-weather-app-backend \
          --region eu-central-1 \
          --query 'taskDefinition' \
          > team2-weather-app-backend.json
          
      - name: Render backend task definition
        id: taskdef
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: team2-weather-app-backend.json
          container-name: backend
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/team2-weather-app-backend:latest

      - name: Deploy Backend Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.taskdef.outputs.task-definition }}
          service: ${{ vars.AWS_ECR_BACKEND_SERVICE }}
          cluster: ${{ vars.AWS_ECR_CLUSTER }}
          force-new-deployment: true
